/*
 * Copyright © 2018 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package co.cask.cdap.api.lineage.operation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Represent the transform operation from collection of inputs to collection of outputs.
 */
public class Transform extends Operation {
  private final List<Input> inputs;
  private final List<String> outputs;

  /**
   * Create the instance of a transform operation.
   * @param name the name of the operation
   * @param description the description of the operation
   * @param inputs the list of inputs for operation
   * @param outputs the array of outputs generated by operation
   */
  public Transform(String name, String description, List<Input> inputs, String ... outputs) {
    this(name, description, inputs, Arrays.asList(outputs));
  }

  /**
   * Create the instance of a transform operation.
   * @param name the name of the operation
   * @param description the description of the operation
   * @param inputs the list of inputs for operation
   * @param outputs the list of outputs generated by operation
   */
  public Transform(String name, String description, List<Input> inputs, List<String> outputs) {
    super(name, Type.TRANSFORM, description);
    this.inputs = Collections.unmodifiableList(new ArrayList<>(inputs));
    this.outputs = Collections.unmodifiableList(new ArrayList<>(outputs));
  }

  /**
   * @return the list of inputs for this transform operation
   */
  public List<Input> getInputs() {
    return inputs;
  }

  /**
   * @return the list of outputs generated by this transform operation
   */
  public List<String> getOutputs() {
    return outputs;
  }
}
